# Page url
baseURL = "https://moonorange.github.io"

languageCode = "en"
DefaultContentLanguage = "en"
HasCJKLanguage = true
enableRobotsTXT = true

# Blog title
title = "Kei's blog"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "Keigo Kida"
    bio = "Software Engineer living in Japan"
    avatar = "img/avatar.jpeg"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Keigo Kida"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#00008b"

# SNS等のユーザー名
[Params.widgets.social]
  github = "moonorange"
  linkedin = "keigo-k-70557314b"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]
