# Page url
baseURL = "https://moonorange.github.io"

languageCode = "en-us"
HasCJKLanguage = true
enableRobotsTXT = true

# Blog title
title = "Kei's Page"

theme = "mainroad"
paginate = 10

[Author]
    name = "Keigo Kida"
    bio = "Software Engineer living in Japan"
    avatar = "img/avatar.jpeg"

[Params]
    description = "Kei's personal blog about tech"
    customCSS = ["css/custom.css"]
    copyright = "Keigo Kida"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true
    toc = true # Enable Table of Contents

[Params.style.vars]
  highlightColor = "#00008b"

[Params.widgets.social]
  github = "moonorange"
  linkedin = "keigo-k-70557314b"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
